version: "3.7"
services:
  backend:
    #build: ./backend
    image: morrismurithi/ip2backend:1.0.2
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/IP2/admin-server/src
    command: npm run start
    networks:
      - IP2-network

  client:
    #build: ./client
    image: morrismurithi/ip2client:1.0.2
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/IP2/admin-client/src
      - ./client/public:/IP2/admin-client/public
    command: npm run start
    networks:
      - IP2-network

networks:
  IP2-network:
    driver: bridge
