FROM node:alpine3.18
# Working Directory
# set the working directory
RUN mkdir -p /IP2/admin-server
WORKDIR /IP2/admin-server
# Copy the package.json file to the working directory
COPY package*.json /IP2/admin-server
# Install the dependencies
RUN npm install --silent
# Copying the rest of the files to the working directory
COPY . /IP2/admin-server
# Running the app
CMD ["npm", "start"]