FROM node:alpine3.18
# Working Directory
# set the working directory
RUN mkdir -p /srv/app/admin-server
WORKDIR /srv/app/admin-server
# Copy the package.json file to the working directory
COPY package*.json /srv/app/admin-server
# Install the dependencies
RUN npm install --silent
# Copying the rest of the files to the working directory
COPY . /srv/app/admin-server
# Running the app
CMD ["npm", "start"]