---
# tasks file for docker-install
- name: Adding The Docker Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding  repository to the sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker 
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Setting up docker user
  ansible.builtin.user:
    name: docker
    groups: "docker"
    append: true
    state: present

- name: Installing Docker module for Python
  ansible.builtin.pip:
    name: docker

- name: Installing Docker Compose
  ansible.builtin.pip:
    name: docker-compose
    state: present

- name: Restarting Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true